name: Master Branch

on:
  push:
    branches:
      - 'release*'

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Maven Install
        run: mvn -B install:install-file -Dfile=lib/validation-report-1.0.0.jar -DgroupId=com.github.hl7-tools -DartifactId=validation-report -Dversion=1.0.0 -Dpackaging=jar
      - name: Maven Clean, Test and Package
        run: mvn -B clean test package site
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          path: extract-validator.jar
      - name: Upload sources
        uses: actions/upload-artifact@v2
        with:
          path: target/extract-validator-sources.jar
      - name: Upload javadoc
        uses: actions/upload-artifact@v2
        with:
          path: target/extract-validator-javadoc.jar
      - name: Upload library
        uses: actions/upload-artifact@v2
        with:
          path: target/lib/
      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          path: target/site/
        
